name: Build iOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS (No-Codesign)
        run: flutter build ios --release --no-codesign

      - name: Zip Runner.app
        run: |
          cd build/ios/iphoneos
          zip -r Runner.app.zip Runner.app

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-runner
          path: build/ios/iphoneos/Runner.app.zip
